### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'save_local'

### ISSUE THREAD

**Issue by jumperche** [caseyjohnsonwv/study-buddy#2]
python app.py
\study-buddy\vectordb.py:90: SyntaxWarning: invalid escape sequence '\s'
  slide_text_cleaned = re.sub('\s+', ' ', shape.text)
\study-buddy\vectordb.py:94: SyntaxWarning: invalid escape sequence '\s'
  slide_notes_cleaned = re.sub('\s+', ' ', slide_notes)
\study-buddy\vectordb.py:102: SyntaxWarning: invalid escape sequence '\s'
  text_splitter = RecursiveCharacterTextSplitter(separators=['\s+'], is_separator_regex=True, keep_separator=True, chunk_size=300, chunk_overlap=0)
\study-buddy\vectordb.py:123: SyntaxWarning: invalid escape sequence '\s'
  page_text_cleaned = re.sub('\s+', ' ', page_text)
\study-buddy\vectordb.py:128: SyntaxWarning: invalid escape sequence '\s'
  text_splitter = RecursiveCharacterTextSplitter(separators=['\s+'], is_separator_regex=True, keep_separator=True, chunk_size=500, chunk_overlap=0)
\study-buddy\vectordb.py:148: SyntaxWarning: invalid escape sequence '\s'
  text_splitter = RecursiveCharacterTextSplitter(separators=['\s+'], is_separator_regex=True, keep_separator=True, chunk_size=1000, chunk_overlap=0)
Generating new embeddings from courses
Using function _load_pptx_docs() to index filetype .pptx
Loaded 0 documents from .pptx files
Using function _load_pdf_docs() to index filetype .pdf
Loaded 0 documents from .pdf files
Using function _load_html_docs() to index filetype .html
Loaded 0 documents from .html files
Traceback (most recent call last):
  File "C:\Users\jump\Documents\R\study-buddy\app.py", line 9, in <module>
    KNOWLEDGEBASE = VectorDB('./courses')
                    ^^^^^^^^^^^^^^^^^^^^^
  File "\study-buddy\vectordb.py", line 60, in __init__
    self._vectorstore.save_local(self._courses_root_path, index_name='index')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save_local'
My path /study-buddy/courses/mathe with 10 pdfs

**Comment by wjcgood1314** [comment]
do you solve it? I have the same problem.

**Comment by wjcgood1314** [comment]
I understand. we should put the materials under courses. Only when there are materials that need to be embedded can self._vectorstore be defined, otherwise it will be None.

**Comment by wjcgood1314** [comment]
I have reproduced it, lucky
